### ISSUE TITLE
Add navbar

### ISSUE THREAD

**Issue by B3ns44d** [TijClass/Wing#1]
@salahhusa9 Your task is to work on the navigation bar

**Comment by salahhusa9** [comment]
@B3ns44d Please change a name, it's wrong

**Comment by B3ns44d** [comment]
> @B3ns44d Please change a name, it's wrong

okay it was a mistake

**Comment by B3ns44d** [comment]
@salahhusa9 navbar is the Code block # 3

**Comment by salahhusa9** [comment]
ok
